In [1]:
import numpy as np
import pandas as pd

In [45]:
# How likely is it that you roll doubles when rolling two dice?
n_trials = n_rows = 1000
n_dice = n_cols = 2
rolls = np.random.choice([1,2,3,4,5,6], n_rows * n_cols).reshape(n_rows,n_cols)
rolls

array([[4, 1],
       [3, 4],
       [6, 2],
       ...,
       [2, 5],
       [6, 3],
       [2, 6]])

In [46]:
sum_by_trial = rolls.sum(axis=1)
sum_by_trial

array([ 5,  7,  8,  9,  8,  7,  8,  6, 11,  2,  8, 10,  6,  5,  8,  4,  3,
        6,  7,  8, 11,  8,  5,  8,  6,  6,  9,  7,  9,  7,  7,  6, 12,  5,
        2,  7,  6,  5,  6,  9,  6,  7,  4,  6,  7, 11,  8,  2,  8,  2,  7,
        8,  4,  8, 10,  7, 11,  8,  8,  6,  5,  6,  5,  5,  7,  8, 10, 11,
        4,  9, 10,  2,  6,  6, 10,  4,  2,  7,  5,  7,  8, 11,  8,  7,  5,
        6,  8,  5,  9,  9,  7,  7,  6,  9, 10,  3,  7,  8, 10,  9,  7,  8,
       10,  6,  7,  7,  5,  7, 12, 11,  9,  7,  4,  7,  7,  7,  4,  3,  7,
        5,  3,  8, 12,  7,  9,  9,  9,  8, 11,  7, 11, 11,  9,  6,  9,  7,
        4,  4,  2,  5,  8,  7,  6,  9,  6,  9,  7, 12,  5,  7,  8,  7,  8,
        5,  9,  7,  8,  9,  4, 11,  6,  4,  4, 12,  6, 11,  8,  8,  5, 12,
        8,  8,  3,  9,  6,  7,  7,  3,  4,  3,  7,  2,  9, 10,  8,  9,  3,
        8,  8,  5,  9, 11,  4,  5,  6,  6,  6,  3,  9, 12, 10, 11, 11,  9,
        6,  8,  5,  7, 11,  4,  3,  8,  6,  6,  9,  8,  6,  9,  4,  5,  4,
        6,  4,  8,  5,  6

In [47]:
doubles = [rolls[x][0] == rolls[x][1] for x in range(0,n_rows)]
pd.Series(doubles).mean()

0.17

In [20]:
#If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of 
# getting more than 3 heads?
n_trials = nrows = 10000
n_coins = ncols = 8

flips = np.random.choice([0,1], n_trials * n_coins).reshape(nrows, ncols)
flips

array([[0, 1, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 0]])

In [21]:
sum_by_trials = flips.sum(axis=1)
sum_by_trials

array([4, 3, 5, ..., 3, 3, 3])

In [10]:
three_heads = sum_by_trials == 3
three_heads

array([ True, False, False, ..., False, False, False])

In [11]:
exactly_3_heads = three_heads.astype(int).mean()
exactly_3_heads

0.2191

In [12]:
more_than_3 = sum_by_trials > 3
more_than_3

array([False,  True,  True, ...,  True,  True,  True])

In [13]:
more_than_3_heads = more_than_3.astype(int).mean()
more_than_3_heads

0.6418

In [22]:
flips = np.random.choice(["Heads","Tails"], n_trials * n_coins).reshape(nrows, ncols)
flips

array([['Tails', 'Tails', 'Heads', ..., 'Tails', 'Heads', 'Heads'],
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Tails', 'Tails'],
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Heads', 'Tails'],
       ...,
       ['Heads', 'Tails', 'Tails', ..., 'Heads', 'Tails', 'Tails'],
       ['Heads', 'Heads', 'Tails', ..., 'Tails', 'Heads', 'Tails'],
       ['Tails', 'Heads', 'Tails', ..., 'Heads', 'Tails', 'Heads']],
      dtype='<U5')

In [23]:
#Using list comprehension to answer
head_bools = [((flips[x] == "Heads").sum() == 3) for x in range(0, nrows)]
pd.Series(head_bools).mean()

0.2304

In [76]:
#3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that
# Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive
# past both have data science students on them?

n_trials = nrows = 10000
#web_dev = 3
#DS = 1
billboards = ncols = 2
probabilities = [.25,.75]

on_bb = np.random.choice(["DS","Webdev"], n_trials * ncols, p = probabilities).reshape(nrows, ncols)
on_bb

array([['Webdev', 'DS'],
       ['Webdev', 'DS'],
       ['DS', 'Webdev'],
       ...,
       ['Webdev', 'Webdev'],
       ['Webdev', 'Webdev'],
       ['Webdev', 'Webdev']], dtype='<U6')

In [77]:
bb_df = pd.DataFrame(on_bb)

In [78]:
bb_df.apply(lambda row: row[0] == row[1] == "DS", axis = 1)

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996     True
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [79]:
bb_df.apply(lambda row: row[0] == row[1] == "DS", axis = 1).mean()

0.0644

In [26]:
#4 Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
# If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able 
# to buy some poptarts on Friday afternoon?
#normal(loc=0.0, scale=1.0, size=None)
n_trials = nrow = 10_000
n_days = ncol = 4
loc = poptarts_bought = 3
scale = std = +-1.5
#normal(loc, scale, size=(nrow,ncol))
poptarts = np.random.normal(3,1.5,(nrow,ncol))
poptarts

array([[2.88376834, 3.8051995 , 1.82642904, 3.74236039],
       [1.96277626, 2.14391606, 2.33034504, 5.75931126],
       [2.51717214, 3.78919526, 2.50660762, 3.47467129],
       ...,
       [4.21982331, 0.57882895, 0.59511092, 1.92323592],
       [3.26343848, 2.49751953, 0.24605862, 2.82840711],
       [3.38899036, 1.81275181, 3.32135556, 4.36189962]])

In [27]:
(poptarts.sum(axis=1) <=16).mean()

0.9149

In [29]:
#5 Compare Heights -- Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

size = n_trials = nrows = 10_000
loc = avg_height = 178
scale = std = 8
#normal(loc=0.0, scale=1.0, size=None)
men = np.random.normal(loc,scale,size)
men

array([179.6754008 , 168.83839013, 177.91594859, ..., 175.16631358,
       178.82538838, 164.15337962])

In [31]:
size = n_trials = nrows = 10_000
loc = avg_height = 170
scale = std = 6
women = np.random.normal(loc,scale,size)
women

array([167.36498943, 164.85914162, 167.61926212, ..., 167.67732008,
       169.99729068, 164.42181735])

In [32]:
(women > men).mean()

0.2114

In [33]:
np.random.normal?