In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

In [15]:
# How likely is it that you roll doubles when rolling two dice?
n_trials = n_rows = 1000
n_dice = n_cols = 2
rolls = np.random.choice([1,2,3,4,5,6], n_rows * n_cols).reshape(n_rows,n_cols)
rolls

array([[3, 4],
       [2, 2],
       [5, 4],
       ...,
       [6, 2],
       [1, 3],
       [1, 5]])

In [41]:
sum_by_trial = rolls.sum(axis=1)
sum_by_trial

In [47]:
doubles = [rolls[x][0] == rolls[x][1] for x in range(0,n_rows)]
pd.Series(doubles).mean()

0.17

In [38]:
# How likely is it that you roll doubles when rolling two dice? Using probability distributions
die_dist = stats.randint(1,7).pmf([3,3])
pd.Series(die_dist).mean()

0.16666666666666666

In [20]:
#If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of 
# getting more than 3 heads?
n_trials = nrows = 10000
n_coins = ncols = 8

flips = np.random.choice([0,1], n_trials * n_coins).reshape(nrows, ncols)
flips

array([[0, 1, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 0]])

In [21]:
sum_by_trials = flips.sum(axis=1)
sum_by_trials

array([4, 3, 5, ..., 3, 3, 3])

In [10]:
three_heads = sum_by_trials == 3
three_heads

array([ True, False, False, ..., False, False, False])

In [11]:
exactly_3_heads = three_heads.astype(int).mean()
exactly_3_heads

0.2191

In [44]:
#If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of 
# getting more than 3 heads?
n = 8
p = .5
# Using probability distribution
exactly3 = stats.binom(n,p).pmf([3,3])
(pd.Series(exactly3)).mean()

0.21875000000000014

In [12]:
more_than_3 = sum_by_trials > 3
more_than_3

array([False,  True,  True, ...,  True,  True,  True])

In [13]:
more_than_3_heads = more_than_3.astype(int).mean()
more_than_3_heads

0.6418

In [42]:
# More than 3 heads
stats.binom(n,p).sf(3)

0.6367187499999999

In [22]:
flips = np.random.choice(["Heads","Tails"], n_trials * n_coins).reshape(nrows, ncols)
flips

array([['Tails', 'Tails', 'Heads', ..., 'Tails', 'Heads', 'Heads'],
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Tails', 'Tails'],
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Heads', 'Tails'],
       ...,
       ['Heads', 'Tails', 'Tails', ..., 'Heads', 'Tails', 'Tails'],
       ['Heads', 'Heads', 'Tails', ..., 'Tails', 'Heads', 'Tails'],
       ['Tails', 'Heads', 'Tails', ..., 'Heads', 'Tails', 'Heads']],
      dtype='<U5')

In [23]:
#Using list comprehension to answer
head_bools = [((flips[x] == "Heads").sum() == 3) for x in range(0, nrows)]
pd.Series(head_bools).mean()

0.2304

In [76]:
#3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that
# Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive
# past both have data science students on them?

n_trials = nrows = 10000
#web_dev = 3
#DS = 1
billboards = ncols = 2
probabilities = [.25,.75]

on_bb = np.random.choice(["DS","Webdev"], n_trials * ncols, p = probabilities).reshape(nrows, ncols)
on_bb

array([['Webdev', 'DS'],
       ['Webdev', 'DS'],
       ['DS', 'Webdev'],
       ...,
       ['Webdev', 'Webdev'],
       ['Webdev', 'Webdev'],
       ['Webdev', 'Webdev']], dtype='<U6')

In [77]:
bb_df = pd.DataFrame(on_bb)

In [78]:
bb_df.apply(lambda row: row[0] == row[1] == "DS", axis = 1)

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996     True
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [79]:
bb_df.apply(lambda row: row[0] == row[1] == "DS", axis = 1).mean()

0.0644

In [46]:
#3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that
# Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive
# past both have data science students on them?
n = 2
p = .25
stats.binom(n,p).pmf([2,2])

array([0.0625, 0.0625])

In [83]:
#4 Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
# If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able 
# to buy some poptarts on Friday afternoon?
#normal(loc=0.0, scale=1.0, size=None)
n_trials = nrow = 100_000
n_days = ncol = 5
loc = poptarts_bought = 3
scale = std = +-1.5
#normal(loc, scale, size=(nrow,ncol))
poptarts = np.random.normal(3,1.5,(nrow,ncol))
poptarts

array([[3.86269215, 4.29954659, 3.64614984, 1.0367463 , 1.66985668],
       [1.3491307 , 2.9259077 , 4.83348357, 5.31611859, 3.60584932],
       [3.65984372, 1.88607951, 2.98103935, 3.45740213, 4.83691321],
       ...,
       [1.07382237, 2.90156463, 2.11014655, 5.54754766, 2.69701236],
       [1.93064396, 6.60555637, 3.72486223, 4.13695008, 4.30252096],
       [1.18617494, 3.66360254, 4.05964428, 1.63996595, 5.72138201]])

In [84]:
(poptarts.sum(axis=1) <17).mean()

0.72424

In [29]:
#5 Compare Heights -- Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

size = n_trials = nrows = 10_000
loc = avg_height = 178
scale = std = 8
#normal(loc=0.0, scale=1.0, size=None)
men = np.random.normal(loc,scale,size)
men

array([179.6754008 , 168.83839013, 177.91594859, ..., 175.16631358,
       178.82538838, 164.15337962])

In [31]:
size = n_trials = nrows = 10_000
loc = avg_height = 170
scale = std = 6
women = np.random.normal(loc,scale,size)
women

array([167.36498943, 164.85914162, 167.61926212, ..., 167.67732008,
       169.99729068, 164.42181735])

In [32]:
(women > men).mean()

0.2114

# 6 When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [43]:
probability = p = [.004, .996] # 1/250 = .004
size = n_trials = nrows = 10_000
nstudents = ncols = 50
ncols2 = 100
# pass or fail = [0,1]


In [40]:
pass_fail = np.random.choice([0,1], n_trials * ncols, p = [.996, .004]).reshape(nrows, ncols)
pass_fail

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [41]:
# Creating a DF. Using the .apply with lambda with sum of tests = 0 or pass
pd.DataFrame(pass_fail).apply(lambda row: sum(row) == 0, axis=1).mean()

0.8135

In [44]:
#Now this is if 100 students installed
pass_fail = np.random.choice([0,1], n_trials * ncols2, p = [.996, .004]).reshape(nrows, ncols2)

In [45]:
pd.DataFrame(pass_fail).apply(lambda row: sum(row) == 0, axis = 1).mean()

0.6744

In [52]:
# What is the probability that we observe an installation issue within the first 150 students that download
# anaconda?
probability = p = [.004, .996] # 1/250 = .004
size = n_trials = nrows = 10_000
nstudents = ncols = 150
# pass or fail = [0,1]
pass_fail = np.random.choice(["pass","fail"], n_trials * ncols, p = [.996, .004]).reshape(nrows, ncols)


In [53]:
#Solving with a pandas series with list comprehension
pd.Series(['fail' in pass_fail[x] for x in range(0,nrows)]).mean()

0.4453

In [59]:
# How likely is it that 450 students all download anaconda without an issue?
probability = p = [.004, .996] # 1/250 = .004
size = n_trials = nrows = 10_000
nstudents = ncols = 450
# pass or fail = [0,1]
pass_fail = np.random.choice(["pass","fail"], n_trials * ncols, p = [.996, .004]).reshape(nrows, ncols)

In [61]:
pd.Series(["fail" not in pass_fail[x] for x in range(0,nrows)]).mean()

0.1657

# 7 There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [69]:
probability = p = [.3, .7]
n_trials = nrows = 10_000
days = ncols = 3
#notruck = 0     truck = 1
food_truck = np.random.choice([0,1], n_trials * ncols, p = [.3,.7]).reshape(nrows,ncols)
food_truck

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       ...,
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 0]])

In [71]:
df = pd.DataFrame(food_truck)
df.apply(lambda row: sum(row) == 0, axis=1).mean()

0.0252

In [72]:
#how likely to not see a truck in 3 days
trial = 10_000
prob = [.7, .3]
days_no = 3
# 1 truck, 0 no_truck
truck = np.random.choice([1, 0], size=(trial, days_no), p=prob)
truck
df = pd.DataFrame(truck)
df["no_truck"] = df.sum(axis=1) == 0
df.no_truck.mean()

0.0281

In [75]:
#Another approach
n_trials = nrows = 10_000
probability = p = [.7,.3]
ndays = ncols = 3
#1 Truck, 0 No Truck
food_truck = np.random.choice([1,0], size = (n_trials,ndays), p=p)
food_truck
df = pd.DataFrame(food_truck)
df["no_truck"] = df.sum(axis=1) == 0

In [76]:
df.no_truck.mean()

0.0268

# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [87]:
n_trials = nrows = 100_000
nbdays = ncols = 23

birthdays = np.random.choice(range(365), size = (n_trials,nbdays))
df = pd.DataFrame(birthdays)
df

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      229  135  155  361   94  283  276  209   52   82  ...  195  266  235   
1      131  318  140  274  105  167  289  306  257  362  ...  359  162  207   
2       76  277  322    7  174   48   99  226  358    6  ...   47  174    4   
3       94  209  133  154  115  342  283  313  197  132  ...  348  221  299   
4       16   81  211   32  160  101  140   53  265  291  ...  235  164   74   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995   37  135  189  344   49   61  298  306   39   69  ...  190  213   14   
99996   50  353   77  341   31  209  100  344  286   38  ...  120   80   40   
99997  152   88  224  215  260  234   26  190  100  168  ...   90   21  242   
99998   49  145   80  185   39  327  198  306  248   45  ...  193  321  181   
99999   91  322  103  155  179  244   52   83  269  212  ...   93   92  152   

        16   17   18   19   20   21   22  
0      240  199  199  126  187  137  154  
1      205  278  136  210  349  178  170  
2       10  351   53  171  317  149   64  
3      342  338  359   56  183  181  188  
4      246    4  295   99  170  270  208  
...    ...  ...  ...  ...  ...  ...  ...  
99995  255  347  149  193  249   90  247  
99996  220  278   58   19  335   37  290  
99997   10  357  254  190  211  351   21  
99998  252  240  140  255  139  331  262  
99999  173  360  139  255  244  143   39  

[100000 rows x 23 columns]

In [88]:
df["n_unique"] = df.nunique(axis=1)
df.head()

0    1    2    3    4    5    6    7    8    9  ...   14   15   16   17  \
0  229  135  155  361   94  283  276  209   52   82  ...  266  235  240  199   
1  131  318  140  274  105  167  289  306  257  362  ...  162  207  205  278   
2   76  277  322    7  174   48   99  226  358    6  ...  174    4   10  351   
3   94  209  133  154  115  342  283  313  197  132  ...  221  299  342  338   
4   16   81  211   32  160  101  140   53  265  291  ...  164   74  246    4   

    18   19   20   21   22  n_unique  
0  199  126  187  137  154        22  
1  136  210  349  178  170        23  
2   53  171  317  149   64        22  
3  359   56  183  181  188        22  
4  295   99  170  270  208        23  

[5 rows x 24 columns]

In [91]:
# If n_unique == 0 then nobody shares a birthday
(df.n_unique != 23).mean()

0.50704

In [96]:
# What about 20 people in the room?
# What is probability that two people share a birthday
n_trials = nrows = 100_000
nbdays = ncols = 20

birthdays = np.random.choice(range(365), size = (n_trials,nbdays))
df = pd.DataFrame(birthdays)
df["n_unique"] = df.nunique(axis=1)
(df.n_unique != 20).mean()

0.41095

In [97]:
# What about 40 people in the room?
# What is probability that two people share a birthday
n_trials = nrows = 100_000
nbdays = ncols = 40

birthdays = np.random.choice(range(365), size = (n_trials,nbdays))
df = pd.DataFrame(birthdays)
df["n_unique"] = df.nunique(axis=1)
(df.n_unique != 40).mean()

0.89163